//! Additive phantom-typestate facade over [`MorphismContext`] (forward arc v1).
//!
//! `Galho<P>` wraps a `MorphismContext` and tags its compile-time phase with a
//! zero-sized [`PhaseState`] marker `P`. The forward-arc transition methods are
//! defined only on the source phase's `Galho<From>` and return `Galho<To>`, so
//! firing a morphism from the wrong phase is a **compile error**, not a runtime
//! precondition failure.
//!
//! This is purely additive: the erased [`MorphismContext`] + [`crate::KnowledgeBase`]
//! surface is unchanged, and the runtime (`galho-cli`) keeps its erased
//! `BTreeMap<String, MorphismContext>`. The typestate is the *authoring* surface
//! for code that statically knows a galho's phase.
//!
//! v1 ships the forward arc only (the apply-before-merge default path). The
//! backward / failure arcs (RevertApply / Abandon / Escalate / Recover / Resume)
//! land in v2 once a consumer needs typed reverse traversal.

use std::marker::PhantomData;

use crate::knowledge::KnowledgeBase;
use crate::morphism::{MorphismContext, MorphismRequirement};
use crate::phase::{MorphismId, Phase};

mod sealed {
    /// Sealed so only the phase ZSTs in this module can implement [`super::PhaseState`].
    pub trait Sealed {}
}

/// A compile-time marker for a galho phase. Implemented only by the zero-sized
/// phase types generated by `phase_state!`. Sealed — downstream crates can't add
/// new phase markers.
pub trait PhaseState: sealed::Sealed {
    /// The runtime [`Phase`] this marker corresponds to.
    const PHASE: Phase;
}

macro_rules! phase_state {
    ($($ty:ident => $phase:ident),+ $(,)?) => {
        $(
            /// Zero-sized typestate marker. See [`PhaseState`].
            #[derive(Debug, Clone, Copy, PartialEq, Eq)]
            pub struct $ty;
            impl sealed::Sealed for $ty {}
            impl PhaseState for $ty {
                const PHASE: Phase = Phase::$phase;
            }
        )+
    };
}

phase_state! {
    Declared => Declared,
    Planned => Planned,
    AppliedPendingReview => AppliedPendingReview,
    ApprovedAwaitingMerge => ApprovedAwaitingMerge,
    Merged => Merged,
    Verified => Verified,
    Done => Done,
}

/// A galho whose phase is known at compile time as `P`. Wraps the erased
/// [`MorphismContext`]; the `PhantomData<P>` carries the compile-time phase tag.
#[derive(Debug, Clone)]
pub struct Galho<P: PhaseState> {
    ctx: MorphismContext,
    _phase: PhantomData<P>,
}

impl<P: PhaseState> Galho<P> {
    /// Borrow the erased context.
    #[must_use]
    pub fn ctx(&self) -> &MorphismContext {
        &self.ctx
    }

    /// Consume into the erased context (drop back to the runtime surface).
    #[must_use]
    pub fn into_ctx(self) -> MorphismContext {
        self.ctx
    }

    /// Re-attach a compile-time phase tag to an erased context. Runtime-checks
    /// that the context's actual phase matches `P::PHASE`; on mismatch returns the
    /// context back unchanged so the caller can recover.
    pub fn assume(ctx: MorphismContext) -> Result<Self, MorphismContext> {
        if ctx.current_phase() == P::PHASE {
            Ok(Self {
                ctx,
                _phase: PhantomData,
            })
        } else {
            Err(ctx)
        }
    }
}

impl Galho<Declared> {
    /// Create a fresh galho in the `Declared` phase.
    #[must_use]
    pub fn declared(galho_name: impl Into<String>) -> Self {
        Self {
            ctx: MorphismContext::declared(galho_name),
            _phase: PhantomData,
        }
    }
}

/// Generates one forward-arc transition method `$method` on `Galho<$from>` that
/// fires `$morphism` via `KnowledgeBase::advance` and re-tags to `Galho<$to>`.
macro_rules! forward_transition {
    ($from:ident, $method:ident, $morphism:ident, $to:ident) => {
        impl Galho<$from> {
            #[doc = concat!("Forward-arc transition firing `", stringify!($morphism), "`.")]
            ///
            /// Consumes `self`; on success returns the next typestate, on
            /// precondition failure returns the unmet requirements with `self`
            /// unchanged.
            pub fn $method(
                mut self,
                kb: &KnowledgeBase,
            ) -> Result<Galho<$to>, (Self, Vec<MorphismRequirement>)> {
                match kb.advance(MorphismId::$morphism, &mut self.ctx) {
                    Ok(_) => Ok(Galho {
                        ctx: self.ctx,
                        _phase: PhantomData,
                    }),
                    Err(missing) => Err((self, missing)),
                }
            }
        }
    };
}

forward_transition!(Declared, plan, Plan, Planned);
forward_transition!(Planned, apply_to_preview, ApplyToPreview, AppliedPendingReview);
forward_transition!(AppliedPendingReview, record_approval, RecordApproval, ApprovedAwaitingMerge);
forward_transition!(ApprovedAwaitingMerge, promote, Promote, Merged);
forward_transition!(Merged, verify, Verify, Verified);
forward_transition!(Verified, seal_done, SealDone, Done);
